image: registry.delite.ca/docker/docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_MODULE_PATH: node_modules/.bin
  MOCHA_BIN: $NODE_MODULE_PATH/mocha
  NODEGYP_BIN: $NODE_MODULE_PATH/node-gyp
  NODEPREGYP_BIN: $NODE_MODULE_PATH/node-pre-gyp
  DOCKER_RUN: docker run --user root -t -e NODE_ENV=test -v $CI_PROJECT_DIR:/deploy $DEV_IMAGE

stages:
  - test

before_script:
  - NODE_ENV=test
  - npm install
  - $NODEPREGYP_BIN build --debug

test:
  image: registry.delite.ca/docker/base/node/10:c-jose
  stage: test
  only:
    - master
  tags:
    - linux
  script:
    - $MOCHA_BIN --timeout 100 "test/**/*.test.js"
