image: registry.delite.ca/docker/docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_MODULE_PATH: node_modules/.bin
  MOCHA_BIN: $NODE_MODULE_PATH/mocha
  DOCKER_RUN: docker run --user root -t -e NODE_ENV=test -v $CI_PROJECT_DIR:/deploy $DEV_IMAGE

stages:
  - test

test:
  image: registry.delite.ca/docker/base/node/c-jose:latest
  stage: test
  only:
    - master
  tags:
    - linux
  script:
    - pwd
    - ls -la
    - npm install
    - $MOCHA_BIN --timeout 100 "test/**/*.test.js"
