image: registry.delite.ca/docker/docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEV_IMAGE: registry.delite.ca/docker/base/node/c-jose:latest
  NODE_MODULE_PATH: node_modules/.bin
  MOCHA_BIN: $NODE_MODULE_PATH/mocha
  DOCKER_RUN: docker run --user node -t -e "NODE_ENV=test" -v "./:/deploy" $DEV_IMAGE

stages:
  - test

test:
  stage: test
  only:
    - master
  tags:
    - linux
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $DEV_IMAGE
    - $DOCKER_RUN $MOCHA_BIN --timeout 100 "test/**/*.test.js"
